name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  # ---- BACKEND JAVA ----
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build & Test
        run: |
          cd backend
          mvn clean package

      - name: Build Docker image
        run: |
          docker build -t infoline-api:latest ./backend

      - name: Deploy sur Kubernetes
        run: |
          kubectl apply -f infrastructure/eks/api-deployment.yaml

  # ---- FRONTEND ANGULAR ----
  build-test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Installer les dépendances
        run: |
          cd frontend/infoline-frontend
          npm install

      - name: Build
        run: |
          cd frontend/infoline-frontend
          npm run build

      - name: Test
        run: |
          cd frontend/infoline-frontend
          npm run test -- --watch=false --browsers=ChromeHeadless